dist: trusty
sudo: false
notifications:
  email: false
env:
  - RELEASE_TAG="release-$TRAVIS_BUILD_NUMBER"
if: tag IS blank


jobs:
  include:
    - stage: build and publish
      language: java
      jdk: openjdk8
      install: skip
      before_script:
        - chmod +x gradlew
      script: ./gradlew clean build
      before_deploy:
        - git config --local user.name "Travis CI"
        - git config --local user.email "travis@example.com"
        - git tag -f $RELEASE_TAG
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: "build/libs/trucker-api-1.0.0.war"
        skip_cleanup: true
    - stage: deploy to cf
      language: bash
      before_script:
        - chmod +x gradlew
      script:
        - echo "Downloading $RELEASE_TAG"
        - wget -P build/libs https://github.com/$GITHUB_USERNAME/fleet-tracker/releases/download/$RELEASE_TAG/trucker-api-1.0.0.war
      before_deploy:
        - echo "Deploying $RELEASE_TAG to Cloud Foundry"
      deploy:
        provider: cloudfoundry
        api: $CF_API_URL
        username: $CF_USERNAME
        password: $CF_PASSWORD
        organization: $CF_ORG
        space: $CF_SPACE